version: "3.9"  # optional since v1.27.0
services:
  web:
    build: .
    container_name: lstm
    
    ports:
      - "8050:8050"
    volumes:
      - .:/app
    restart: unless-stopped
    command: >
      bash -c "
      source venv/bin/activate
      && python -m pip install --upgrade pip
      && pip install -r requirements.txt
      && python dashboard.py
      "
    expose:
      - 8050